# Generated by Django 6.0.5 on 2026-05-23 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('service_requests', '0002_servicerequest_assigned_to_servicerequest_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='service_requests.servicerequest'),
        ),
    ]
