# Generated by Django 6.0.5 on 2026-05-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_servicerequest_assigned_to_servicerequest_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='service_requests/%Y/%m/%d/'),
        ),
    ]
